[package]
name = "teamspeak3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "wayhouse sniffer: recognises the TeamSpeak 3 voice server's TS3INIT1 client init packet."

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wayhouse-sniffer-abi = { path = "../wayhouse-sniffer-abi" }
